
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: storage
  dashboards:
    energy-dashboard:
      mode: yaml
      title: Energie
      icon: mdi:home-lightning-bolt-outline
      show_in_sidebar: true
      filename: custom_yaml/dashboards/energy.yaml
