
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include custom_yaml/templates.yaml
modbus: !include custom_yaml/modbus/daikin-homehub.yaml

lovelace:
  mode: storage
  resources:
    - url: /local/energy-entity-row.js
      type: module
  dashboards:
    energy-dashboard:
      mode: yaml
      title: Energie
      icon: mdi:home-lightning-bolt-outline
      show_in_sidebar: true
      filename: custom_yaml/dashboards/energy.yaml
