- trigger:
    - platform: time_pattern
      seconds: "/20"
  sensor:
    - name: "KasiCharger Bezug gesamt (korrigiert)"
      unique_id: kasicharger_bezug_gesamt_korrigiert
      icon: mdi:ev-plug-type2
      state: >
        {{((states('sensor.kasicharger_total_energy_charged') |int - 22000000) |int / 1000 )| round(2)}}
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
